title: GSoC-2025
url: https://rkt-1597.github.io/GSoC-2025-Blogs-RTEMS
author: Prithvi Tambewagh
email: 
description: > 
  Blogs during GSoC p2025 period at RTEMS for the project - Providing SPARC GRETH Network Drivers for lwIP
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%d %b %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.instagram.com/sra_vjti/
      icon: instagram
      color: pink
    - url: https://www.linkedin.com/company/society-of-robotics-and-automation-vjti/
      icon: linkedin
      color: blue
    - url: https://www.facebook.com/pg/sra.vjti/posts/
      icon: facebook
      color: cyan
    - url: https://www.youtube.com/channel/UC-g67CbV2Iu30n7TvipRiCA/featured
      icon: youtube
      color: red
    - url: https://github.com/sra-vjti
      icon: github-square
      color: yellow

# Build settings
remote_theme: bitbrain/jekyll-dash

plugins:
  - liquid-md5
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging
  
avatar_source: github
github_username: sra-vjti
